### ISSUE TITLE
Using MinPubSub with Sockets

### ISSUE THREAD

**Issue by scazzy** [daniellmb/MinPubSub#12]
Would like to know how can I use it with socket  implementation.
I'm building a notification/messaging service (not-node.js based), and wanted a lightweight pubsub architecture that can connect to the socket and do the pub-sub calling.

Have you tried it?

**Comment by daniellmb** [comment]
It should be possible to wire MinPubSub into your socket both client-side and server-side. For example, if you are using [Socket.io](http://socket.io/) the method `socket.on()` is similar to `subscribe()` and `socket.emit` is similar to `publish()`. Your front end might look something like this:

```javascript
// listen for when the server emits the new message topic
socket.on('new message', function (data) {
 // update the UI with the new message
 publish('new message', data);
});
```
