### ISSUE TITLE
Unsubscribe by topic name

### ISSUE THREAD

**Issue by yaruson** [daniellmb/MinPubSub#15]
Hello, I think it could be nice to have a method to unsubscribe all listeners from certain topic (or list of topics) by its name. It might be convenient, as user will have no need to store all the handles to perform a cleanup. What do you think about this suggestion?

**Comment by daniellmb** [comment]
Thanks for the suggestion! Nice idea, but I can't think of a good way to support that API change that's backwards compatable with how it works today.
